### ISSUE TITLE
Can't get past square one

### ISSUE THREAD

**Issue by kenahoo** [SineSwiper/Dist-Zilla-TravisCI#15]
I can't seem to figure out what I need to add to my `dist.ini` (or perhaps other stuff) to get my distribution to test with Travis.  My build has no `.travis.yml` file generated:

https://travis-ci.org/kenahoo/Path-Class/builds/17453497

I pretty much blindly copied the example stuff from the `TravisYML` docs into my `dist.ini`:

https://github.com/kenahoo/Path-Class/blob/master/dist.ini

Any pointers?

**Comment by SineSwiper** [comment]
Closing older ticket...
