### ISSUE TITLE
List::AllUtils::pairs needs 0.04 or later

### ISSUE THREAD

**Issue by yak1ex** [SineSwiper/Dist-Zilla-TravisCI#19]
List::AllUtils::pairs appears in 0.04 or later.
http://search.cpan.org/~drolsky/List-AllUtils-0.03/lib/List/AllUtils.pm
http://search.cpan.org/~drolsky/List-AllUtils-0.04/lib/List/AllUtils.pm

When I had 0.03 only, tests failed in updating this module.
I'm not sure what is your preferable way to specify a version of a prereq, so I don't make a pull request.

**Comment by SineSwiper** [comment]
This was fixed in 1.12
