### ISSUE TITLE
Please, please, please, remove `use sanity` from App::Command::chainsmoke

### ISSUE THREAD

**Issue by kentfredric** [SineSwiper/Dist-Zilla-TravisCI#31]
sanity doesn't really do CPAN users any favours here. It loads a lot of stuff that while (debateably) useful for developers, having it in your module is a sizeable blight on every dzil install that has it with zero benefit for the user.

I mentioned this in pull #24 but I was obviously not loud enough.

Because every command is loaded on every command, every useless dependency you put in there makes every command suffer.

For instance, having `chainsmoke` installed presently for means I have a minimum time of `0.6` seconds to run `dzil version`.

Simply commenting out `use sanity` in chainsmoke.pm reduces my `dzil version` time to `0.1` seconds, removes 20 modules from startup, and removes 23 files from the total IO's required.

**Comment by gempesaw** [comment]
!! wow, i had just gotten used to the idea of having a slow `dzil` :(

thanks for the fix and the release :D
