### ISSUE TITLE
Travis failing to build a dist::zilla distribution with Perl 5.8

### ISSUE THREAD

**Issue by bluescreen10** [SineSwiper/Dist-Zilla-TravisCI#8]
When TravisCI tries to run the "install" phase it fails with the folllowing:

Successfully installed MooseX-AttributeShortcuts-0.019
! Installing the dependencies failed: Installed version (5.008009) of perl is not in range '5.010'
! Bailing out the installation for Dist-Zilla-Plugin-Git-2.014.
8 distributions installed
! Configure failed for Dist-Zilla-TravisCI-1.03. See /home/travis/.cpanm/work/1372186011.894/build.log for details.
You have Dist::Zilla::Plugin::UploadToCPAN (4.300034)
5 distributions installed

**Comment by SineSwiper** [comment]
This has already been split and released a while ago.
